# Generated by Django 2.2.10 on 2020-05-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailListModel',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('main_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopListModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('memo', models.CharField(max_length=100)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDetailListModel',
            fields=[
                ('sub_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('main_content', models.CharField(max_length=100)),
                ('hp_url', models.CharField(blank=True, max_length=200, null=True)),
                ('map_url', models.CharField(blank=True, max_length=200, null=True)),
                ('root_url', models.CharField(blank=True, max_length=200, null=True)),
                ('content1', models.CharField(blank=True, max_length=100, null=True)),
                ('content2', models.CharField(blank=True, max_length=100, null=True)),
                ('content3', models.CharField(blank=True, max_length=100, null=True)),
                ('content4', models.CharField(blank=True, max_length=100, null=True)),
                ('content5', models.CharField(blank=True, max_length=100, null=True)),
                ('content6', models.CharField(blank=True, max_length=100, null=True)),
                ('content7', models.CharField(blank=True, max_length=100, null=True)),
                ('content8', models.CharField(blank=True, max_length=100, null=True)),
                ('content9', models.CharField(blank=True, max_length=100, null=True)),
                ('content10', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarkapp.DetailListModel')),
            ],
        ),
        migrations.AddField(
            model_name='detaillistmodel',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarkapp.TopListModel'),
        ),
    ]
