# Generated by Django 3.0 on 2020-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='toplistmodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
