# Generated by Django 3.0 on 2020-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkapp', '0002_auto_20200516_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillistmodel',
            name='hp_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detaillistmodel',
            name='map_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detaillistmodel',
            name='root_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
