# Generated by Django 3.0 on 2020-06-04 22:50

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkapp', '0002_auto_20200603_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdetaillistmodel',
            name='images',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='toplistmodel',
            name='images',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
    ]
