# Generated by Django 3.0 on 2020-05-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkapp', '0005_auto_20200516_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdetaillistmodel',
            old_name='content',
            new_name='main_content',
        ),
        migrations.RemoveField(
            model_name='detaillistmodel',
            name='hp_url',
        ),
        migrations.RemoveField(
            model_name='detaillistmodel',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='detaillistmodel',
            name='root_url',
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='hp_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='map_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='root_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
