# Generated by Django 3.0 on 2020-05-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarkapp', '0006_auto_20200517_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdetaillistmodel',
            name='content1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
